# File probably auto-generated by Django [95], maybe django-admin startapp
# [79, "startapp" documentation]


# This line appears to have been created when this file was created by
# django-admin startapp [79, "startapp" documentation]
from django.contrib import admin

from settings.models import Shoe, WorkoutType

admin.site.register(Shoe)
admin.site.register(WorkoutType)
