# File probably auto-generated by Django [95], maybe django-admin startapp
# [79, "startapp" documentation]

# This line appears to have been created when this file was created by
# django-admin startapp [79, "startapp" documentation]
from django.contrib import admin

from shared.models import UserInfo, Follow, Block

admin.site.register(UserInfo)
admin.site.register(Follow)
admin.site.register(Block)
