# File probably auto-generated by Django [95], maybe django-admin startapp
# [79, "startapp" documentation]. The contents of this file were also possibly
# created by that as well.

from django.test import TestCase

# Create your tests here.
